[package]
name = "my-iced-project"
version = "0.1.0"
edition = "2021" # 2024 also works, but most crates still default to 2021

[dependencies]
iced = { git = "https://github.com/iced-rs/iced" }
tokio = { version = "1", features = ["full"] }
